WITH temp_vault as(

SELECT 
CUS_CUST_ID, 
SIT_SITE_ID,
KYC_ENTITY_TYPE,
KYC_KNOWLEDGE_LEVEL,
KYC_NAME_BRAND,
KYC_COMP_CORPORATE_NAME,
KYC_COMP_SOCIETY_TYPE,
KYC_COMP_INCOME,
KYC_COMP_IDNT_ID,
KYC_COMP_IDNT_NUMBER,
KYC_COMP_IDNT_TYPE,
KYC_LAST_UPDATED_DT,
KYC_LAST_UPDATED_DTTM,
AUD_UPD_DT,
AUD_UPD_DTTM

from `meli-bi-data.WHOWNER.LK_KYC_VAULT_USER`

WHERE KYC_ENTITY_TYPE = 'company' 
)

select SIT_SITE_ID, KYC_KNOWLEDGE_LEVEL, count(KYC_COMP_IDNT_NUMBER) from temp_vault
group by 1,2


select SIT_SITE_ID, KYC_KNOWLEDGE_LEVEL, KYC_COMP_SOCIETY_TYPE, count(distinct KYC_COMP_IDNT_NUMBER) from temp_vault
group by 1,2,3